#config_version=6

coils:
  c_trough_eject:
    number: 07
    default_pulse_ms: 50
    tags: ball_launch
  c_drop_target_right:
    number: 05
    default_pulse_ms: 50
  c_knocker:
    number: 06
    default_pulse_ms: 50
  c_upper_left_sling:
    number: 08
    default_pulse_ms: 50
  c_saucer:
    number: 09
    default_pulse_ms: 50
  c_drop_target_left:
    number: 10
    default_pulse_ms: 50
  c_left_pop_bumper:
    number: 11
    default_pulse_ms: 50
  c_right_pop_bumper:
    number: 12
    default_pulse_ms: 50
  c_middle_pop_bumper:
    number: 13
    default_pulse_ms: 50
  c_right_sling:
    number: 14
    default_pulse_ms: 50
  c_left_sling:
    number: 15
    default_pulse_ms: 50
  c_coin_lockout:
    number: 19