#config_version=6

## MPF Main Machine Config File
#
# This file defines your system-wide properties like switches,
# drivers, ball devices, hardware platforms, and more. You can
# include everything here, or create sub-config files to be
# imported and merged with this one.

hardware:
  platform: lisy
lisy:
  connection: serial
  port: com3
  baud: 115200

config:
  - config_ball_devices.yaml
  - config_coils.yaml
  - config_switches.yaml
  - config_lights.yaml
  - config_sounds.yaml

game:
  balls_per_game: 3        # Number of balls per player per game
  max_players: 4           # Maximum players allowed

modes:
  - attract
  - base
  - escape_graveyard

playfields:
  playfield:
    default_source_device: bd_trough
    tags: default
    
digital_outputs:
  flipper_enabling_relay:
    type: driver
    number: 16
    enable_events: ball_started
    disable_events: ball_will_end

autofire_coils:
  ac_left_sling:
    coil: c_left_sling
    switch: s_left_sling
  ac_right_sling:
    coil: c_right_sling
    switch: s_right_sling
  ac_upper_left_sling:
    coil: c_upper_left_sling
    switch: s_left_upper_bumper
  ac_left_pop_bumper:
    coil: c_left_pop_bumper
    switch: s_left_pop_bumper
  ac_right_pop_bumper:
    coil: c_right_pop_bumper
    switch: s_right_pop_bumper
  ac_middle_pop_bumper:
    coil: c_middle_pop_bumper
    switch: s_middle_pop_bumper

ball_saves:
  default_ball_save:
    active_time: 10s              # how long the save is active after ball start
    enable_events: ball_started   # start automatically at the beginning of each ball
    auto_launch: true             # auto-eject the saved ball
    balls_to_save: 1              # only one save per ball
    eject_delay: 1s            # optional: delay before eject